### ISSUE TITLE
[CLI]Support for Named Address

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#118]
Support for defining a named address in `Move.toml` file as follows:

```toml
[addresses]
rooch_demo = ""
```

Then specify the specific address of the named address during build or publish:

```shell
rooch move build --named-addresses rooch_demo=default
```
