### ISSUE TITLE
[CLI] Cannot compile Move contracts when dependent on the git repository

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#330]
Configure the dependencies in Move.toml as the git repository, like this:

```toml
[package]
name = "RoochDemo"
version = "0.0.1"

[dependencies]
MoveosStdLib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/moveos-stdlib", rev = "main" }
#MoveosStdlib = { local = "../../rooch/moveos/moveos-stdlib/moveos-stdlib" }

[addresses]
rooch_demo = "_"
moveos_std = "0x2"
rooch_framework = "0x3"
```

Run:

```shell
rooch move build --named-addresses rooch_demo={ACCOUNT_ADDR}
UPDATING GIT DEPENDENCY https://github.com/rooch-network/rooch.git
```

The compilation will error out:

```shell
Error: Failed to resolve dependencies for package 'RoochDemo'
```

If the dependency is changed to local (that is, changed to look like the line that is commented out), it works.

Are there some problems?
