### ISSUE TITLE
[cli] add rooch ws relay command and serve it as CLI tool

### ISSUE THREAD

**Issue by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [rooch-network/rooch#407]
Part of #406 

It will be added as ws relay in the rooch.yaml file as an example below:

```yml
envs:
- alias: default
  rpc: http://0.0.0.0:50051
  ws: ws://0.0.0.0:8080
active_env: default
```
